---

- name: Add database
  community.postgresql.postgresql_db:
    name: "{{ item.value.name }}"
    owner: "{{ item.value.owner }}"
    encoding: "{{ item.value.encoding | default('UTF-8') }}"
    lc_collate: "{{ item.value.lc_collate | default('en_US.utf8') }}"
    lc_ctype: "{{ item.value.lc_ctype | default('en_US.utf8') }}"
    template: template0
    login_host: "localhost"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    login_port: "{{ postgres_port }}"
  loop: "{{ postgres_databases | dict2items }}"
  loop_control:
    label: "{{ item.value.name }}"
