---

- name: Install python library
  pip: name={{ item }}
  loop:
    - psycopg2-binary

- name: Deploy postgresql server
  community.docker.docker_compose:
    project_name: postgres
    definition:
      version: "3.6"
      services:
        db:
          image: "{{ postgres_image }}"
          container_name: "{{ postgres_container_name }}"
          hostname: postgres
          environment:
            POSTGRES_USER: "{{ postgres_user }}"
            POSTGRES_PASSWORD: "{{ postgres_password }}"
            POSTGRES_DB: "{{ postgres_db }}"
          restart: always
          ports:
            - "{{ postgres_port }}:5432"
          volumes:
             - postgres:/var/lib/postgresql/data
      volumes:
        postgres:
