---

- name: Deploy Prometheus stack
  kubernetes.core.helm:
    name: grafana
    chart_ref: "{{ chart }}"
    release_namespace: "{{ release_namespace }}"
    update_repo_cache: yes
    values:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 256Mi
      persistence:
        size: 5Gi
        storageClassName: openebs-hostpath
      datasources:
        datasources.yaml:
           apiVersion: 1
           datasources:
           - name: Prometheus
             type: prometheus
             url: http://prometheus-server.monitoring
             access: proxy
             isDefault: true
      sidecar:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi

