---

- name: Add dashboard service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: traefik-dashboard
        namespace: "{{ release_namespace }}"
      spec:
        ports:
        - port: 9000
          targetPort: 9000
        selector:
          app.kubernetes.io/name: traefik

- name: Add auth secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-authsecret
        namespace: "{{ release_namespace }}"
      type: kubernetes.io/basic-auth
      data:
        username: "{{ traefik_dashboard_username|b64encode }}"
        password: "{{ traefik_dashboard_password|b64encode }}"

- name: Add redirect middleware
  kubernetes.core.k8s:
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: dashboard-redirectscheme
        namespace: "{{ release_namespace }}"
      spec:
        redirectScheme:
          scheme: https
          permanent: true

- name: Add auth middleware
  kubernetes.core.k8s:
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: dashboard-auth
        namespace: "{{ release_namespace }}"
      spec:
        basicAuth:
          secret: dashboard-authsecret

- name: Add insecure ingress route
  kubernetes.core.k8s:
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: dashboard-insecure
        namespace: "{{ release_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - kind: Rule
            match: "{{ traefik_dashboard }}"
            middlewares:
              - name: dashboard-redirectscheme
                namespace: "{{ release_namespace }}"
            services:
              - kind: Service
                name: traefik-dashboard
                namespace: "{{ release_namespace }}"
                port: 9000

- name: Add ingress route
  kubernetes.core.k8s:
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: dashboard
        namespace: "{{ release_namespace }}"
      spec:
        entryPoints:
          - websecure
        routes:
          - kind: Rule
            match: "{{ traefik_dashboard }}"
            middlewares:
              - name: dashboard-auth
                namespace: "{{ release_namespace }}"
            services:
              - kind: Service
                name: traefik-dashboard
                namespace: "{{ release_namespace }}"
                port: 9000
        tls:
          certResolver: letsencrypt
