---

- name: Add namespace
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ release_namespace }}"
    state: present

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: "{{ release_name }}"
    repo_url: "{{ repo }}"
