---

- name: Deploy Minio server
  community.docker.docker_compose:
    project_name: minio
    definition:
      version: "3.6"
      services:
        broker:
          image: "{{ minio_image }}"
          container_name: "{{ minio_container_name }}"
          command: server /data --console-address ":9001"
          environment:
            MINIO_ROOT_USER: "{{ minio_user }}"
            MINIO_ROOT_PASSWORD: "{{ minio_password }}"
          labels:
            - "traefik.enable=true"
            - "traefik.http.services.minio.loadbalancer.server.port=9000"
            - "traefik.http.middlewares.minio-redirectscheme.redirectscheme.scheme=https"
            - "traefik.http.middlewares.minio-redirectscheme.redirectscheme.permanent=true"
            - "traefik.http.routers.minio-insecure.rule=Host(`{{ minio_domain }}`)"
            - "traefik.http.routers.minio-insecure.entrypoints=web"
            - "traefik.http.routers.minio-insecure.middlewares=semaphore-redirectscheme@docker"
            - "traefik.http.routers.minio.rule=Host(`{{ minio_domain }}`)"
            - "traefik.http.routers.minio.entrypoints=websecure"
            - "traefik.http.routers.minio.tls.certresolver=le"
          networks:
            - proxy
          restart: always
          ports:
            - "{{ minio_console_port }}:9001"
          volumes:
             - data:/data
      networks:
        proxy:
          external:
            name: "{{ proxy_network }}"
      volumes:
        data:
