---

- name: Deploy Traefik
  community.docker.docker_compose:
    project_name: traefik
    definition:
      version: "3.6"
      services:
        traefik:
          image: "{{ traefik_image }}"
          container_name: "{{ traefik_container_name }}"
          command:
            - "--api.insecure=true"
            - "--metrics.prometheus=true"
            - "--metrics.prometheus.addEntryPointsLabels=true"
            - "--metrics.prometheus.addrouterslabels=true"
            - "--metrics.prometheus.entryPoint=metrics"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entryPoints.metrics.address=:8088"
            - "--certificatesresolvers.le.acme.httpchallenge=true"
            - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.le.acme.email={{ traefik_le_email }}"
            - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
          networks:
            - proxy
          ports:
            - "{{ traefik_web_port }}:80"
            - "{{ traefik_websecure_port }}:443"
            - "8080:8080"
            - "8088:8088"
          restart: always
          volumes:
            - "traefik:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
      networks:
        proxy:
          name: "{{ proxy_network }}"
      volumes:
        traefik:
