---

repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
release_name: nfs-subdir-external-provisioner
release_namespace: nfs

nfs_server: 127.0.0.1
nfs_storage_path: /var/local

nfs_storage_class:
  name: nfs-client
  reclaimPolicy: Delete
  archiveOnDelete: true
  accessModes: ReadWriteMany
  volumeBindingMode: WaitForFirstConsumer
