name: Lint

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install requirements
        run: pip install poetry

      - name: Prepare environment
        run: make install

      - name: Run linter
        run: make lint
